/* Generated By:JavaCC: Do not edit this line. BuilderParserDemoConstants.java */
package cs524builder.parserdemo;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BuilderParserDemoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 9;
  /** RegularExpression Id. */
  int DAN = 11;
  /** RegularExpression Id. */
  int STU = 12;
  /** RegularExpression Id. */
  int ASSIGN = 13;
  /** RegularExpression Id. */
  int COLON = 14;
  /** RegularExpression Id. */
  int COMMA = 15;
  /** RegularExpression Id. */
  int LBRACE = 16;
  /** RegularExpression Id. */
  int RBRACE = 17;
  /** RegularExpression Id. */
  int LBRACKET = 18;
  /** RegularExpression Id. */
  int RBRACKET = 19;
  /** RegularExpression Id. */
  int LPAREN = 20;
  /** RegularExpression Id. */
  int RPAREN = 21;
  /** RegularExpression Id. */
  int SEMICOLON = 22;
  /** RegularExpression Id. */
  int SQUOTE = 23;
  /** RegularExpression Id. */
  int DQUOTE = 24;
  /** RegularExpression Id. */
  int PATTERN_DECIMAL = 25;
  /** RegularExpression Id. */
  int LITERAL_NUMBER = 26;
  /** RegularExpression Id. */
  int LITERAL_INTEGER = 27;
  /** RegularExpression Id. */
  int LITERAL_REAL = 28;
  /** RegularExpression Id. */
  int LITERAL_STRING = 29;
  /** RegularExpression Id. */
  int IDENTIFIER = 30;
  /** RegularExpression Id. */
  int LETTER = 31;
  /** RegularExpression Id. */
  int DIGIT = 32;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\f\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"//\"",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "<token of kind 10>",
    "\"dan\"",
    "\"stu\"",
    "\"=\"",
    "\":\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "<PATTERN_DECIMAL>",
    "<LITERAL_NUMBER>",
    "<LITERAL_INTEGER>",
    "<LITERAL_REAL>",
    "<LITERAL_STRING>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
  };

}
